% m3-sys/llvm/src/m3makefile
% This is the Modula-3 binding to the C binding to the llvm infrastructure. 

import ("libm3")
Module ("LLVMTypes") 
Interface ("LLVM") 
Interface ("M3DIB") 

include_dir("llvmlibs")

build_standalone ()
Library ("llvm")

